apiVersion: v1
kind: Service
metadata:
  name: azure-vm-status-api
  labels:
    app: azure-vm-status-api
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5001
    protocol: TCP
  selector:
    app: azure-vm-status-api 